# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

#   config.vm.network :forwarded_port, guest: 8080, host: 80

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playground.yml"

  end
end
