---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: yes
    - name: start nginx
      service:
        name: nginx
        state: started
      become: yes
    - name: copy the nginx config file and restart nginx
      copy:
        src: nginx-first-take.cfg
        dest: /etc/nginx/sites-available/nginx-first-take.cfg
      become: yes
    - name: create symlink
      file:
        src: /etc/nginx/sites-available/nginx-first-take.cfg
        dest: /etc/nginx/sites-enabled/default
        state: link
      become: yes
    - name: copy the content of the web site
      copy:
        src: static_content/
        dest: /var/www/nginx-first-take
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes

